### ISSUE TITLE
Resize large images

### ISSUE THREAD

**Issue by TriForceX** [gregoriodelasheras/gregoriodelasheras.github.io#1]
To improve page load speed (specially on mobile devices) i recommend to resize **f-01.jpg** and **f-02.jpg**. The maximum recommended size for large images on a website is up to 1920px width (for banners, sliders, backgrounds or any full-size image). In your case both images are 2000px, which does not make much sense since they are being used in a 300px container.

In other hand resizing these images to 300px will not be good for mobile phones due most devices are 720px, so i would recommend you to resize the images up to 2x of its container size (600px).

**Comment by gregoriodelasheras** [comment]
Thank you very much @TriForceX! It took me a while to correct the mistake because I was focused on other small projects. However, I just fixed the issue following your advice. Below is the link to the latest update where the issue is resolved.

Fix: https://github.com/gregoriodelasheras/gregoriodelasheras.github.io/commit/30f85d0e36ca1162ee7f9a6130559a4e53e655a9

Thank you very much again, best regards!
Francisco Gregorio de las Heras
